### ISSUE TITLE
K8S 入门

### ISSUE THREAD

**Issue by Caaalabash** [Caaalabash/blog-frontend#107]
## 1. K8S基础概念

参考:

[kuboard - 学习Kubernetes基础知识](https://kuboard.cn/learning/k8s-basics/kubernetes-basics.html)

[阳明 - 使用YAML 文件创建 Kubernetes Deployment](https://www.qikqiak.com/post/use-yaml-create-kubernetes-deployment/)

### 1.1 集群

![K8S-集群](https://static.calabash.top/blog-media/file/file-QQ20210317-105748.png)

上图描述的是拥有一个 Master 节点和三个 Worker 节点的 K8S 集群。

+ Master节点：负责协调集群中的所有活动，例如调度应用程序、维护应用程序的状态、拓展和更新应用程序。
+ Worker节点：是 VM 或物理计算机，充当 K8S 集群中的工作计算机。

### 1.2 节点

![K8S-节点](https://static.calabash.top/blog-media/file/file-QQ20210317-110412.png)

上图描述的是一个 Node 和 4 个 Pod。

+ 每个 Node 都由 Master 管理。一个 Node 可以有多个 Pod，Master 会根据每个 Node 上可用资源的情况，自动调度 Pod 到最佳的 Node 上。
+ 每个 Node 至少运行：
    + Kubelet：负责 Master 和 Worker 之间通信的进程；管理 Pod 和 Pod 内运行的 Container
    + 容器运行环境（如Docker）：负责下载镜像、创建和运行容器

### 1.3 容器组

![K8S-容器组](https://static.calabash.top/blog-media/file/file-QQ20210317-111121.png)

Pod 是 K8S 中的一个抽象的概念，用于存放一组 container （可能包含一个或多个 container 容器，即图上的正方体），
以及这些 container 的一些共享资源，例如：

+ 共享存储，称为卷，即紫色圆柱
+ 网络：每个 Pod 在集群中有一个唯一的 IP，Pod 中的 container 共享该 IP 地址
+ container 的基本信息：例如容器的镜像版本，对外暴露的端口

关于 Pod 的更多信息：

+ Pod（容器组）是 k8s 集群上的最基本的单元。
+ 当我们在 k8s 上创建 Deployment 时，会在集群上创建包含容器的 Pod (而不是直接创建容器)。
+ 每个Pod都与运行它的 worker 节点（Node）绑定，并保持在那里直到终止或被删除。
+ 如果节点（Node）发生故障，则会在集群中的其他可用节点（Node）上运行相同的 Pod（从同样的镜像创建 Container，使用同样的配置，IP 地址不同，Pod 名字不同）。
+ 如果多个容器紧密耦合并且需要共享磁盘等资源，则他们应该被部署在同一个Pod（容器组）中。

### 1.4 kubectl

kubectl 命令行工具管理控制 Kubernetes 集群。更多的命令/参数还是在使用中列出。

建议使用[https://github.com/kubermatic/fubectl](https://github.com/kubermatic/fubectl)，简化 `kubectl` 命令，因为`kubectl`是在太难敲了

### 2.1 "搭建"一个K8S集群

从实践和学习的角度搭建一个K8S集群，只有一句话：**选择云服务商的 容器服务 > 集群 > 新建集群 > 买2～3个按量付费的工作节点**

### 2.2 创建一个Pod

基础概念中提到："Pod 是 K8S 集群中的最基本的单元"，那么接下来就是创建一个Pod的流程：

````yaml
apiVersion: apps/v1                   # 声明K8s的API版本
kind: Pod                             # 声明API对象的类型，这里是Pod，还有Deployment、Job、Ingress、Service等
metadata:                             # 设置Pod的元数据
  name: nginx-pod                     # pod名称，namespace内唯一
spec:                                 # 配置Pod的具体规格
  containers:                         # 容器规格
    - name: front-end                 # 容器名称，pod内唯一
      image: nginx
````

创建Pod

````
kubectl create -f pod.yaml
````

查看Pod相关信息

````
kubectl get pods
kubectl get pod [PodName]
kubectl get pod [PodName] --output yaml/json
kubectl get pods -o wide  // 查看pods所在的运行节点
kubectl describe pod [PodName]
````

删除Pod

````
kubectl delete -f pod.yaml
kubectl delete pod hello-world
kubectl delete pod --all
````

更新Pod

````
kubectl replace -f pod.yaml
kubectl replace --force -f pod.yaml
````

访问:

````
curl podIp:containerPort
````

### 2.3 创建一个Deployment

在上面的例子中，只是单纯的创建了一个`Pod`实例，但是如果这个`Pod`出现了故障的话，我们的服务就挂掉了。
所以kubernetes提供了一个Deployment的概念，可以让kubernetes去管理一组 POD 的副本，也就是副本集，这样就可以保证一定数量的副本一直可用的，
不会因为一个 POD 挂掉导致整个服务挂掉。我们可以这样定义一个Deployment：

````yaml
apiVersion: apps/v1                         
kind: Deployment                      # Deployment     
metadata:
  name: nginx-deployment
spec:
  replicas: 2                         # 使用该Deployment创建2个Pod
  selector:                           # 必填字段
    matchLabels:                      # 选择Pod
      app: nginx
  template:                           # Pod模版
    metadata: 
      labels:                         # Pod的标签
        app: nginx
    spec:                             # Pod的具体规格
      containers:
      - name: nginx
        image: nginx
````

应用yaml文件

````
k apply -f [yaml文件或所在目录]
````

状态，此时可以访问`172.16.0.9:80`、`172.16.0.24:80`

````
[root@VM-0-8-tlinux ~]# k get pods -o wide
NAME                               READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
nginx-deployment-f89759699-hpz5v   1/1     Running   0          18s   172.16.0.9    172.17.0.8    <none>           <none>
nginx-deployment-f89759699-vzjbt   1/1     Running   0          18s   172.16.0.24   172.17.0.17   <none>           <none>
````

### 2.4 创建一个Service

基础概念中提到："每个Pod都有一个唯一的Ip地址"，Pod 在销毁、创建过程中会带来的 IP 地址的变化，因此服务的访问不能依赖 Pod 的ip地址。

![K8S - 服务](https://static.calabash.top/blog-media/file/file-QQ20210317-174515.png)

上图图中有两个服务Service A(黄色虚线)和Service B(蓝色虚线) Service A 将请求转发到 IP 为 `10.10.10.1` 的Pod上， 
Service B 将请求转发到 IP 为 `10.10.10.2`、`10.10.10.3`、`10.10.10.4` 的Pod上。

通过创建Service，指定`spec.type`，可以以不同方式向外暴露应用程序

+ `ClusterIP`：在集群的内部IP上暴露服务，这种方式只有集群内部可以访问到
+ `NodePort`：通过每个节点上的 IP 和静态端口（NodePort）暴露服务，可以通过`<节点 IP>:<节点端口>`访问
+ `LoadBalancer`：使用云提供商的负载均衡器向外部暴露服务

定义一个`service.yml`

````yaml
apiVersion: apps/v1                   
kind: Service                         # Service
metadata:
  name: nginx-service
spec:
  type: NodePort                      # Service类型
  selector:
    app: nginx
  ports:
    - port: 80                        # 集群内的其他容器组可通过 80 端口访问 Service
      targetPort: 80                  # 将请求转发到匹配 Pod 的 80 端口
      nodePort: 30007                 # 通过任意节点的 30007 端口访问 Service
````

执行

````
k apply -f service.yml
````

查看状态：

````
[root@VM-0-8-tlinux ~]# k get nodes
NAME          STATUS   ROLES    AGE     VERSION
172.17.0.17   Ready    <none>   3h16m   v1.18.4-tke.6
172.17.0.8    Ready    <none>   3h16m   v1.18.4-tke.6

[root@VM-0-8-tlinux ~]# k get services -o wide
NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE     SELECTOR
kubernetes      ClusterIP   172.16.255.225   <none>        443/TCP        3h11m   <none>
nginx-service   NodePort    172.16.255.247   <none>        80:30007/TCP   171m    app=nginx
````

此时可以访问：

+ `<service-ip>:<port>`，即：`172.16.255.247:80`
+ `<node-ip>:<nodePort>`，即：`172.17.0.17:30007`、`172.17.0.8:30007`
+ `<pod-ip>:<targetPort>`：略

### 2.5 服务和标签

![K8S - 服务和标签](https://static.calabash.top/blog-media/file/file-QQ20210317-174659.png)

上图体现了 Label 和 LabelSelector 之间的关联关系

+ Deployment B 含有 LabelSelector 为 app=B 通过此方式声明含有 app=B 标签的 Pod 与之关联
+ 通过 Deployment B 创建的 Pod 包含标签为 app=B
+ Service B 通过标签选择器 app=B 选择可以路由的 Pod
