### ISSUE TITLE
云服务器配置代理流程记录

### ISSUE THREAD

**Issue by Caaalabash** [Caaalabash/blog-frontend#98]
## 国内码农需要战胜网络环境

前置条件

+ 云服务器(docker/docker-compose)
+ 使用clash且有一份配置

### 关于http_proxy和https_proxy

很多程序会自动识别HTTP_PROXY ， HTTPS_PROXY 环境变量，然后决定是否走代理, 永久写入环境变量就完事咯:

执行`vim ~/.bashrc`, 在末尾添加

````
// 这里的端口需要和下文中使用的保持一致
export http_proxy=localhoost:7890
export https_proxy=localhost:7890
````

### 使用docker启动clash容器

````
docker pull dreamacro/clash
````

编辑`docker-compose.yml`

````
version: '3'
services:
  clash:
    image: dreamacro/clash:latest
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    restart: always
    network_mode: "host"
    container_name: clash
````

编辑配置文件`config.yaml`, 配置参考地址[github clash wiki](https://github.com/Dreamacro/clash/wiki/configuration),
如果本地有的话, scp到云服务器即可.

几个关键的配置:

````
# http/https代理端口
port: 7890
# SOCKS5 代理端口
socks-port: 7891
# Linux 和 macOS 的 redir 代理端口
redir-port: 7892
# 允许局域网的连接
allow-lan: true
# 日志界别
log-level: info
# Clash 的 RESTful API
external-controller: '0.0.0.0:9090'
````

接下来:

+ 云服务器安全组开启`9090`端口
+ `docker-compose up -d`启动容器

一切就绪, 但默认选择的节点可能失败, 切换节点见下方

### linux下clash如何选择节点

可以通过`http://localhost:9000`下的restful api调用, 但不够直观, 推荐使用可视化界面[http://clash.razord.top/#/settings](http://clash.razord.top/#/settings)

![](https://static.calabash.top/blog-media/file/file-QQ20201022-002157@2x.png)

在外部控制设置中填写服务器ip和端口, 然后在代理页面选择区服之类的信息即可

### 结果

![](https://static.calabash.top/blog-media/file/file-QQ20201022-002630@2x.png)
